### ISSUE TITLE
No Auth Provider found for name "azure"

### ISSUE THREAD

**Issue by devteng** [maorfr/helm-backup#2]
Hi, I ran into this on Windows 10 using git-bash for Azure's AKS

$ helm backup svfb --tiller-namespace svfb
2018/11/29 16:00:20 No Auth Provider found for name "azure"
Error: plugin "backup" exited with error

How do I enable debug? This message coming from Kube or Helm is vague.

**Comment by maorfr** [comment]
This is coming from kube. I'll add a fix for it.

**Comment by maorfr** [comment]
Hey @devteng,

I added a fix. can you remove and re-install the plugin and see how it goes?
also added some log messages ;)

**Comment by devteng** [comment]
Looks good!! Thank you for the fix! Both backup and restore works perfect.

**Comment by maorfr** [comment]
Glad to hear. Enjoy ;)
