### ISSUE TITLE
Not working with microk8s installation (conjure up)

### ISSUE THREAD

**Issue by reyou** [maorfr/helm-backup#4]
Hello,

On my local, I have microk8s installed via conjure up, and it does not have following file. I think it is not created for minikube as well.

```
/home/shipahi/.kube/config
```

I am getting following error.
```
helm backup default
2018/12/31 01:13:21 getting tiller storage
2018/12/31 01:13:21 stat /home/shipahi/.kube/config: no such file or directory
```

any idea or improvement suggestions on this?
If you need credentials, maybe we can supply auth token value?

**Comment by maorfr** [comment]
I think that this might help:
https://github.com/ubuntu/microk8s/blob/master/README.md#accessing-kubernetes

Specifically:
```
snap alias microk8s.kubectl kubectl
microk8s.kubectl config view --raw > $HOME/.kube/config
```
Be careful with these commands if you have additional clusters.

Let me know if that works for you ;)

**Comment by maorfr** [comment]
Feel free to reopen if needed
