### ISSUE TITLE
Error: unknown flag: --kubeconfig

### ISSUE THREAD

**Issue by judexzhu** [maorfr/helm-backup#6]
I use `--kubeconfig` to manage multiple kubernetes clusters.

but however, looks like the backup plugin not support this flag

```
$ helm --kubeconfig=~/.kube/config  backup -h
Error: unknown flag: --kubeconfig
Usage:
  backup [flags] NAMESPACE

Flags:
      --file string               file name to use (.tgz file). If not provided - will use <namespace>.tgz
  -h, --help                      help for backup
  -l, --label string              label to select tiller resources by (default "OWNER=TILLER")
  -r, --restore                   restore instead of backup
      --tiller-namespace string   namespace of Tiller (default "kube-system")

Error: plugin "backup" exited with error
```
Thanks for the plugins

**Comment by maorfr** [comment]
hey @judexzhu,

Correct, the `kubeconfig` flag is not implemented. You can use the `KUBECONFIG` environment variable instead. Let me know if this works for you!

**Comment by judexzhu** [comment]
Hi @maorfr

Thank you for your reply and sorry for late

I tested it, and it works for me 

Thank you so much 👍 

Jude
